seo: 
  site_name: 
  title: 
  description: 
  keywords: 
  social_image: 
  author: 
  favicon_image: 
social: 
  instagram_username:
  facebook_url:
  twitter_username: 
design: 
  dark-featured_color: '#182987'
  medium-featured_color: 
  light-featured_color: 
  dark_color: 'rgb(27,27,27)'
  light_color: '#ffffff'
  accent_color: '#ae0001'