seo: 
  site_name: 
  title: 
  description: 
  keywords: 
  social_image: 
  author: 
  favicon_image: 
social: 
  instagram_username:
  facebook_url:
  twitter_username: 
design: 
  dark-featured_color: '#0a2265'
  medium-featured_color: '#1b5a93'
  light-featured_color: '#5296b4'
  dark_color: 'rgb(27,27,27)'
  light_color: '#ffffff'
  accent_color: '#879618'